version: "3.8"

services:
  postgres:
    image: postgres:15
    container_name: postgres_db
    restart: always
    environment:
      POSTGRES_USER: myuser
      POSTGRES_PASSWORD: mypassword
      POSTGRES_DB: mydatabase
    ports:
      - "5433:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  redis:
    image: redis:7
    container_name: redis_cache
    restart: always
    ports:
      - "6379:6379"

  backend:
    build: ./backend
    container_name: backend_app
    restart: always
    depends_on:
      - postgres
      - redis
    environment:
      DATABASE_URL: postgresql://myuser:mypassword@postgres:5432/mydatabase
      REDIS_URL: redis://redis:6379
    ports:
      - "8000:8000"

  frontend:
    build: ./frontend
    container_name: frontend_app
    restart: always
    depends_on:
      - backend
    environment:
      NEXT_PUBLIC_REDIS_URL: redis://redis:6379
    ports:
      - "3000:3000"

  storybook:
    build:
      context: ./frontend
      dockerfile: Dockerfile.storybook
    container_name: storybook_ui
    restart: always
    ports:
      - "6006:6006"

volumes:
  postgres_data:
